apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k
    spec:
      containers:
        - name: k
          image: "localhost:32000/k:1.0"
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: root
            - name: MONGO_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: k-service
  labels:
    name: k-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: k
  selector:
    app: k
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "docker.io/bitnami/mongodb:4.0.8"
          env:
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongo
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-password: "c2VjcmV0"
---

