apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: "localhost:32000/mongo:4.1.9"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongo
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-password: "c2VjcmV0"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k-snapshot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k-snapshot
    spec:
      containers:
        - name: k-snapshot
          image: 'localhost:32000/k-snapshot:1.0-SNAPSHOT'
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: mongoadmin
            - name: MONGO_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k-snapshot-service
  labels:
    name: k-snapshot-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: k
  selector:
    app: k-snapshot
  type: ClusterIP

